# This is the final, complete CircleCI config file.
# It will build, test, push to ECR, and deploy to EKS.
version: 2.1

# 1. Orbs (reusable packages) for AWS and Kubernetes
orbs:
  aws-ecr: circleci/aws-ecr@9.0.2
  aws-cli: circleci/aws-cli@4.1.2
  kubernetes: circleci/kubernetes@1.3.1

# 2. Jobs (the "what")
jobs:
  # This job just builds and tests your Vite app
  build-and-test:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Project
          command: npm run build
      # We don't need to persist to workspace because
      # the next job will re-checkout the code to build
      # the Docker image from scratch.

  # This job builds the Docker image and pushes it to your ECR
  build-and-push-image:
    # This job runs in a machine executor to build Docker images
    machine:
      image: ubuntu-2004:2022.01.2
    steps:
      - checkout
      - aws-cli/setup:
          region: ${AWS_REGION}
      - aws-ecr/build-and-push-image:
          # This is the ECR repository name you created
          repo: pixcraft-repo
          region: ${AWS_REGION}
          # This sets the image tag to "latest"
          tag: "latest"
          # This must match the ECR_REGISTRY_URL variable
          registry-id: AWS_ECR_REGISTRY_ID

  # This job deploys your application to the EKS cluster
  deploy-to-kubernetes:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - aws-cli/setup:
          region: ${AWS_REGION}
      - kubernetes/install
      - run:
          name: "Configure Kubectl for EKS"
          # This command logs kubectl into your EKS cluster
          command: |
            aws eks update-kubeconfig \
              --name pixcraft-cluster \
              --region ${AWS_REGION}
      - run:
          name: "Deploy to EKS"
          # This applies your Kubernetes config files
          command: |
            kubectl apply -f k8s/deployment.yaml
            kubectl apply -f k8s/service.yaml
            # This forces the deployment to restart with the new image
            kubectl rollout restart deployment/pixcraft-deployment

# 3. Workflows (the "how and when")
workflows:
  build-test-and-deploy:
    jobs:
      # 1. Run the build/test job first
      - build-and-test

      # 2. After build-and-test, run the image push
      - build-and-push-image:
          requires:
            - build-and-test
          context:
            # "aws-creds" is the name of the Context
            # we will create in CircleCI
            - aws-creds
          filters:
            branches:
              only:
                - main  # Only run this on the main branch

      # 3. After the image is pushed, deploy to Kubernetes
      - deploy-to-kubernetes:
          requires:
            - build-and-push-image
          context:
            - aws-creds
          filters:
            branches:
              only:
                - main  # Only run this on the main branch
